- name: Install Apache2
  hosts: slave1
  become: true
  tasks:
    - name: Install Apache2
      apt:
        name: apache2
        state: present

- name: Install nginx
  hosts: slave2
  become: true
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
